#!/usr/bin/env python3
"""
Self-Improving Reindex Script
Updates index.md with current state of ~/self-improving/
"""

import os
import re
from datetime import datetime
from pathlib import Path

# Paths - Priority: Existing ~/self-improving/ > Merged location
# This ensures backwards compatibility for users who already installed Self-Improving

_SCRIPT_DIR = Path(__file__).parent
_ORIGINAL_DIR = Path.home() / "self-improving"
_MERGED_DIR = _SCRIPT_DIR.parent  # ~/.openclaw/skills/fts5/self_improving

# Prefer existing installation (don't overwrite user's data)
if _ORIGINAL_DIR.exists():
    SELF_IMPROVING_DIR = _ORIGINAL_DIR
    print(f"📌 Using existing Self-Improving: {SELF_IMPROVING_DIR}")
elif (_MERGED_DIR / "memory.md").exists():
    SELF_IMPROVING_DIR = _MERGED_DIR
    print(f"📌 Using merged Self-Improving: {SELF_IMPROVING_DIR}")
else:
    # New install - use merged location
    SELF_IMPROVING_DIR = _MERGED_DIR
    print(f"📌 New installation at: {SELF_IMPROVING_DIR}")

INDEX_FILE = SELF_IMPROVING_DIR / "index.md"
MEMORY_FILE = SELF_IMPROVING_DIR / "memory.md"
DOMAINS_DIR = SELF_IMPROVING_DIR / "domains"
PROJECTS_DIR = SELF_IMPROVING_DIR / "projects"
ARCHIVE_DIR = SELF_IMPROVING_DIR / "archive"
CORRECTIONS_FILE = SELF_IMPROVING_DIR / "corrections.md"


def count_lines(file_path: Path) -> int:
    """Count lines in a file."""
    if not file_path.exists():
        return 0
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return len(f.readlines())
    except:
        return 0


def get_topic_references(file_path: Path, topic: str) -> int:
    """Count how many times a topic is referenced in a file."""
    if not file_path.exists():
        return 0
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # Count occurrences of topic keyword
            return len(re.findall(rf'\b{re.escape(topic)}\b', content, re.IGNORECASE))
    except:
        return 0


def scan_domains() -> list:
    """Scan domains directory and return list of topics."""
    if not DOMAINS_DIR.exists():
        return []
    
    topics = []
    for f in DOMAINS_DIR.glob("*.md"):
        topics.append({
            "name": f.stem,
            "file": f.name,
            "lines": count_lines(f),
            "updated": datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d")
        })
    return topics


def scan_projects() -> list:
    """Scan projects directory and return list of projects."""
    if not PROJECTS_DIR.exists():
        return []
    
    projects = []
    for f in PROJECTS_DIR.glob("*.md"):
        projects.append({
            "name": f.stem,
            "file": f.name,
            "lines": count_lines(f),
            "updated": datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d")
        })
    return projects


def get_recent_corrections() -> list:
    """Get recent corrections from corrections.md."""
    if not CORRECTIONS_FILE.exists():
        return []
    
    try:
        with open(CORRECTIONS_FILE, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            # Get last 10 corrections
            return lines[-10:] if len(lines) > 10 else lines
    except:
        return []


def generate_index_content() -> str:
    """Generate updated index.md content."""
    domains = scan_domains()
    projects = scan_projects()
    
    # Calculate stats
    total_entries = 1 + len(domains) + len(projects)  # memory.md + domains + projects
    
    # Find hot topics (referenced multiple times in memory.md)
    hot_topics = []
    if MEMORY_FILE.exists():
        try:
            with open(MEMORY_FILE, 'r', encoding='utf-8') as f:
                content = f.read()
                # Simple heuristic: topics mentioned in memory
                for d in domains:
                    ref_count = get_topic_references(MEMORY_FILE, d["name"])
                    if ref_count > 0:
                        hot_topics.append({
                            "name": d["name"],
                            "references": ref_count
                        })
        except:
            pass
    
    # Sort hot topics by reference count
    hot_topics.sort(key=lambda x: x["references"], reverse=True)
    top_hot = hot_topics[:5] if len(hot_topics) > 5 else hot_topics
    
    lines = []
    lines.append("# Knowledge Index")
    lines.append("")
    lines.append("> Auto-generated by reindex script. Last update: " + datetime.now().strftime("%Y-%m-%d %H:%M"))
    lines.append("")
    lines.append("## 📊 Statistics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total entries | {total_entries} |")
    lines.append(f"| Last update | {datetime.now().strftime('%Y-%m-%d %H:%M')} |")
    lines.append(f"| Hot topics | {len(hot_topics)} |")
    lines.append(f"| Archived topics | {len(list(ARCHIVE_DIR.glob('*.md'))) if ARCHIVE_DIR.exists() else 0} |")
    lines.append("")
    lines.append("## 🔥 Hot Topics (最近被引用)")
    lines.append("")
    if top_hot:
        lines.append("| Topic | References |")
        lines.append("|-------|------------|")
        for t in top_hot:
            lines.append(f"| {t['name']} | {t['references']} |")
    else:
        lines.append("*None yet - memory.md will track references when loaded.*")
    lines.append("")
    lines.append("## 📚 Domain Index")
    lines.append("")
    if domains:
        lines.append("| Topic | File | Lines | Last Updated |")
        lines.append("|-------|------|-------|--------------|")
        for d in sorted(domains, key=lambda x: x["name"]):
            lines.append(f"| {d['name']} | {d['file']} | {d['lines']} | {d['updated']} |")
    else:
        lines.append("*No domain files found.*")
    lines.append("")
    lines.append("## 📁 Project Index")
    lines.append("")
    if projects:
        lines.append("| Project | File | Lines | Last Updated |")
        lines.append("|---------|------|-------|--------------|")
        for p in sorted(projects, key=lambda x: x["name"]):
            lines.append(f"| {p['name']} | {p['file']} | {p['lines']} | {p['updated']} |")
    else:
        lines.append("*No project files found.*")
    lines.append("")
    lines.append("## 📝 Recent Corrections")
    lines.append("")
    recent_corrections = get_recent_corrections()
    if recent_corrections:
        lines.append("| Timestamp | Correction |")
        lines.append("|-----------|------------|")
        for c in recent_corrections[-5:]:  # Last 5
            c = c.strip()
            if c:
                # Simple formatting - just show first 50 chars
                display = c[:50] + "..." if len(c) > 50 else c
                lines.append(f"| | {display} |")
    else:
        lines.append("*No corrections logged yet.*")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Auto-generated by `scripts/reindex.py`*")
    
    return "\n".join(lines)


def main():
    print("🔄 Self-Improving Reindex...")
    
    # Check directory
    if not SELF_IMPROVING_DIR.exists():
        print(f"❌ {SELF_IMPROVING_DIR} does not exist")
        return 1
    
    # Generate new index content
    content = generate_index_content()
    
    # Write to index.md
    with open(INDEX_FILE, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Index updated: {INDEX_FILE}")
    print(f"   Topics: {len(scan_domains())}")
    print(f"   Projects: {len(scan_projects())}")
    
    return 0


if __name__ == "__main__":
    exit(main())